[package]
name = "rust_ext"
version = "0.1.0"
authors = ["Hongyi Duan <hd162@duke.edu>"]
edition = "2018"

[lib]
name = "rust_ext"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.3", features = ["extension-module"] }
