name: Python CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Rust and Maturin
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          pip install maturin

      - name: Build Rust extension
        run: |
          maturin develop

      - name: Run Python tests
        run: |
          python -m unittest discover
